### PR TITLE
Home & category page UI

### PR DESCRIPTION
**Pull request by Varun-28**
Added UI for home page and category page.

- added navbar
- added footer
- Users can go to the category page from the home page and see a list of quizzes available

Screenshot 2022-04-01 at 00-39-57 MACTS - Quiz
Screenshot 2022-04-01 at 00-40-13 MACTS - Quiz

### CODE REVIEW

**Review by AnuragSahu11 — APPROVED** [review]
Relative units can be used instead of px in some places, also color variables could be used, other than that , UI is cool, banner looks great. Ready to merge. Looking forward to AOT quiz.

**Review by shilpe26 — APPROVED** [review]
▪️Good File Structuring
▪️The naming convention is easy to read 
▪️Good to use Page not found feature
▪️Good to merge the file

**Review by RakshithBhat03 — APPROVED** [review]
The code is clean and well structured. UI looks amazing.

**Comment by Varun-28** [comment]
> Relative units can be used instead of px in some places, also color variables could be used, other than that , UI is cool, banner looks great. Ready to merge. Looking forward to AOT quiz.

Done changes as suggested ✅

**Pull request merged**
